#!/usr/bin/env node
/**
 * Dessau — write the verification table into the architecture page.
 *
 *   node scripts/sync-checks.mjs
 *   node scripts/sync-checks.mjs --check   # verify only, exit 1 if stale
 *
 * -----------------------------------------------------------------------------
 * Why this is generated
 * -----------------------------------------------------------------------------
 *
 * A list of "the checks that exist" is the first documentation to go stale, because
 * adding a check is satisfying and updating the table about it is not. The version in
 * `agent/architecture.md` was missing four scripts within a week of them being
 * written — including the one that gates the whole reference.
 *
 * A stale list of checks is worse than no list, because it is used to answer "is this
 * covered?". Answering that wrongly is how a gap survives.
 *
 * So both halves are derived:
 *
 *   - WHICH checks exist comes from the `check:*` scripts in `package.json`, which is
 *     also what actually runs. A script nobody wired into `npm run check` is not a
 *     gate, and will not appear here.
 *   - WHAT each one catches comes from a `@catches` line in the script's own header
 *     comment, so the description lives next to the implementation.
 *
 * @catches A stale verification table on the architecture page, and a check script
 *   that never says what it catches.
 *
 * Zero dependencies, Node stdlib only.
 */

import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK_ONLY = process.argv.includes('--check');

const PAGE = join(ROOT, 'reference/architecture.html');
const START = '<!-- DDS_CHECK_TABLE:START — generated by scripts/sync-checks.mjs. Do not edit. -->';
const END = '<!-- DDS_CHECK_TABLE:END -->';

/* ------------------------------------------------------------------ collect */

const pkg = JSON.parse(await readFile(join(ROOT, 'package.json'), 'utf8'));

/**
 * Every script `npm run check` actually runs, in the order it runs them.
 *
 * Read from the aggregate rather than from the `check:*` keys, because the order is
 * information: the cheap structural checks run before the slow ones, so a broken
 * stylesheet is reported before a contrast sweep spends time on it.
 */
const aggregate = pkg.scripts?.check ?? '';
const ordered = [...aggregate.matchAll(/npm run (check:[\w:-]+)/g)].map((m) => m[1]);

const rows = [];
const problems = [];

for (const name of ordered) {
  const command = pkg.scripts[name];

  if (!command) {
    problems.push(`package.json: \`npm run check\` calls "${name}", which is not defined`);
    continue;
  }

  // A step may run more than one script; each gets its own row.
  for (const file of [...command.matchAll(/(scripts\/[\w.-]+\.mjs)/g)].map((m) => m[1])) {
    let source;
    try {
      source = await readFile(join(ROOT, file), 'utf8');
    } catch {
      problems.push(`${name}: ${file} does not exist`);
      continue;
    }

    /**
     * `@catches` in the header comment. Deliberately a required tag rather than
     * something inferred from prose: a script whose author never said what it catches
     * has not finished explaining itself, and a guess here would read as fact.
     */
    const catches = source.match(/^\s*\*\s*@catches\s+(.+)$/m);

    if (!catches) {
      problems.push(
        `${file} has no \`@catches\` line in its header comment, so the architecture ` +
          `page cannot say what it is for`
      );
      continue;
    }

    rows.push({
      script: file,
      npm: name,
      catches: catches[1].trim(),
      // Whether the step is a verify-only run of a generator.
      generated: /--check/.test(command),
    });
  }
}

if (problems.length) {
  console.error('');
  for (const problem of problems) console.error(`  ${problem}`);
  console.error(`\n${problems.length} problem(s). The table was not written.\n`);
  process.exit(1);
}

/* -------------------------------------------------------------------- render */

const escape = (text) =>
  String(text).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

const table = `${START}
          <div class="dds-scroll">
            <table class="dds-table dds-text-sm">
              <caption class="dds-visually-hidden">
                Every check run by npm run check, and what each one catches
              </caption>
              <thead>
                <tr>
                  <th scope="col">Script</th>
                  <th scope="col">Catches</th>
                </tr>
              </thead>
              <tbody>
${rows
  .map(
    (row) => `                <tr>
                  <th scope="row"><code class="dds-code">${escape(
                    row.script.replace('scripts/', '')
                  )}</code>${
                    row.generated
                      ? '<br><span class="dds-text-2xs dds-text-muted">verify only · regenerate to fix</span>'
                      : ''
                  }</th>
                  <td>${escape(row.catches)}</td>
                </tr>`
  )
  .join('\n')}
              </tbody>
            </table>
          </div>
          <p class="dds-text-sm dds-text-subtle dds-mbs-sm">
            All of it zero-dependency, Node standard library only. One command:
            <code class="dds-code">npm run check</code>.
          </p>
          ${END}`;

/* --------------------------------------------------------------------- write */

const page = await readFile(PAGE, 'utf8');

const startAt = page.indexOf(START);
const endAt = page.indexOf(END);

if (startAt === -1 || endAt === -1) {
  console.error(
    `\nCannot run: reference/architecture.html has no generated block.\n\n` +
      `Add these two markers where the table belongs:\n\n  ${START}\n  ${END}\n`
  );
  process.exit(1);
}

const updated = page.slice(0, startAt) + table + page.slice(endAt + END.length);

if (CHECK_ONLY) {
  if (updated === page) {
    console.log(`reference/architecture.html check table is current (${rows.length} checks).`);
    process.exit(0);
  }
  console.error(
    'reference/architecture.html check table is STALE — run: node scripts/sync-checks.mjs'
  );
  process.exit(1);
}

await writeFile(PAGE, updated, 'utf8');
console.log(`Wrote the check table into reference/architecture.html — ${rows.length} checks.`);
